// Sistema de Conquistas e Badges
// Conquistas são desbloqueadas automaticamente baseadas em progresso

import { Achievement } from './db/schema';

export interface AchievementDefinition {
  id: string;
  type: Achievement['type'];
  name: string;
  description: string;
  icon: string;
  category: Achievement['category'];
  requirement: number;
  xpReward: number;
  checkProgress: (stats: any) => number;
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // BRONZE - Iniciante
  {
    id: 'first-habit',
    type: 'habit',
    name: 'Primeiro Passo',
    description: 'Complete seu primeiro hábito',
    icon: '🌱',
    category: 'bronze',
    requirement: 1,
    xpReward: 50,
    checkProgress: (stats) => stats.habitsCompleted || 0,
  },
  {
    id: 'first-task',
    type: 'task',
    name: 'Produtivo',
    description: 'Complete sua primeira tarefa',
    icon: '✅',
    category: 'bronze',
    requirement: 1,
    xpReward: 50,
    checkProgress: (stats) => stats.tasksCompleted || 0,
  },
  {
    id: 'first-pomodoro',
    type: 'study',
    name: 'Focado',
    description: 'Complete seu primeiro Pomodoro',
    icon: '🍅',
    category: 'bronze',
    requirement: 25,
    xpReward: 50,
    checkProgress: (stats) => stats.totalFocusTime || 0,
  },
  {
    id: 'streak-3',
    type: 'streak',
    name: 'Consistente',
    description: 'Mantenha uma sequência de 3 dias',
    icon: '🔥',
    category: 'bronze',
    requirement: 3,
    xpReward: 100,
    checkProgress: (stats) => stats.currentStreak || 0,
  },

  // SILVER - Intermediário
  {
    id: 'habits-10',
    type: 'habit',
    name: 'Construtor de Hábitos',
    description: 'Complete 10 hábitos',
    icon: '💪',
    category: 'silver',
    requirement: 10,
    xpReward: 200,
    checkProgress: (stats) => stats.habitsCompleted || 0,
  },
  {
    id: 'tasks-25',
    type: 'task',
    name: 'Executor',
    description: 'Complete 25 tarefas',
    icon: '⚡',
    category: 'silver',
    requirement: 25,
    xpReward: 200,
    checkProgress: (stats) => stats.tasksCompleted || 0,
  },
  {
    id: 'focus-10h',
    type: 'study',
    name: 'Mente Afiada',
    description: 'Acumule 10 horas de foco',
    icon: '🧠',
    category: 'silver',
    requirement: 600,
    xpReward: 300,
    checkProgress: (stats) => stats.totalFocusTime || 0,
  },
  {
    id: 'streak-7',
    type: 'streak',
    name: 'Semana Perfeita',
    description: 'Mantenha uma sequência de 7 dias',
    icon: '🌟',
    category: 'silver',
    requirement: 7,
    xpReward: 300,
    checkProgress: (stats) => stats.currentStreak || 0,
  },
  {
    id: 'clean-7',
    type: 'addiction',
    name: 'Força de Vontade',
    description: 'Fique 7 dias limpo',
    icon: '💎',
    category: 'silver',
    requirement: 7,
    xpReward: 500,
    checkProgress: (stats) => stats.cleanDays || 0,
  },

  // GOLD - Avançado
  {
    id: 'habits-50',
    type: 'habit',
    name: 'Mestre dos Hábitos',
    description: 'Complete 50 hábitos',
    icon: '👑',
    category: 'gold',
    requirement: 50,
    xpReward: 500,
    checkProgress: (stats) => stats.habitsCompleted || 0,
  },
  {
    id: 'tasks-100',
    type: 'task',
    name: 'Máquina de Produtividade',
    description: 'Complete 100 tarefas',
    icon: '🚀',
    category: 'gold',
    requirement: 100,
    xpReward: 500,
    checkProgress: (stats) => stats.tasksCompleted || 0,
  },
  {
    id: 'focus-50h',
    type: 'study',
    name: 'Estudioso Dedicado',
    description: 'Acumule 50 horas de foco',
    icon: '📚',
    category: 'gold',
    requirement: 3000,
    xpReward: 800,
    checkProgress: (stats) => stats.totalFocusTime || 0,
  },
  {
    id: 'streak-30',
    type: 'streak',
    name: 'Mês Imparável',
    description: 'Mantenha uma sequência de 30 dias',
    icon: '🏆',
    category: 'gold',
    requirement: 30,
    xpReward: 1000,
    checkProgress: (stats) => stats.currentStreak || 0,
  },
  {
    id: 'clean-30',
    type: 'addiction',
    name: 'Transformação',
    description: 'Fique 30 dias limpo',
    icon: '🦋',
    category: 'gold',
    requirement: 30,
    xpReward: 1500,
    checkProgress: (stats) => stats.cleanDays || 0,
  },

  // PLATINUM - Expert
  {
    id: 'habits-200',
    type: 'habit',
    name: 'Lenda dos Hábitos',
    description: 'Complete 200 hábitos',
    icon: '⚔️',
    category: 'platinum',
    requirement: 200,
    xpReward: 1500,
    checkProgress: (stats) => stats.habitsCompleted || 0,
  },
  {
    id: 'tasks-500',
    type: 'task',
    name: 'Titã da Produtividade',
    description: 'Complete 500 tarefas',
    icon: '🎯',
    category: 'platinum',
    requirement: 500,
    xpReward: 2000,
    checkProgress: (stats) => stats.tasksCompleted || 0,
  },
  {
    id: 'focus-200h',
    type: 'study',
    name: 'Mestre do Conhecimento',
    description: 'Acumule 200 horas de foco',
    icon: '🎓',
    category: 'platinum',
    requirement: 12000,
    xpReward: 3000,
    checkProgress: (stats) => stats.totalFocusTime || 0,
  },
  {
    id: 'streak-100',
    type: 'streak',
    name: 'Centenário',
    description: 'Mantenha uma sequência de 100 dias',
    icon: '💯',
    category: 'platinum',
    requirement: 100,
    xpReward: 5000,
    checkProgress: (stats) => stats.currentStreak || 0,
  },
  {
    id: 'clean-90',
    type: 'addiction',
    name: 'Renascimento',
    description: 'Fique 90 dias limpo',
    icon: '🌅',
    category: 'platinum',
    requirement: 90,
    xpReward: 5000,
    checkProgress: (stats) => stats.cleanDays || 0,
  },

  // DIAMOND - Lendário
  {
    id: 'habits-1000',
    type: 'habit',
    name: 'Imortal dos Hábitos',
    description: 'Complete 1000 hábitos',
    icon: '💠',
    category: 'diamond',
    requirement: 1000,
    xpReward: 10000,
    checkProgress: (stats) => stats.habitsCompleted || 0,
  },
  {
    id: 'tasks-2000',
    type: 'task',
    name: 'Deus da Produtividade',
    description: 'Complete 2000 tarefas',
    icon: '⚡',
    category: 'diamond',
    requirement: 2000,
    xpReward: 10000,
    checkProgress: (stats) => stats.tasksCompleted || 0,
  },
  {
    id: 'focus-1000h',
    type: 'study',
    name: 'Sábio Supremo',
    description: 'Acumule 1000 horas de foco',
    icon: '🔮',
    category: 'diamond',
    requirement: 60000,
    xpReward: 15000,
    checkProgress: (stats) => stats.totalFocusTime || 0,
  },
  {
    id: 'streak-365',
    type: 'streak',
    name: 'Ano Perfeito',
    description: 'Mantenha uma sequência de 365 dias',
    icon: '🌈',
    category: 'diamond',
    requirement: 365,
    xpReward: 20000,
    checkProgress: (stats) => stats.currentStreak || 0,
  },
  {
    id: 'clean-365',
    type: 'addiction',
    name: 'Liberdade Total',
    description: 'Fique 365 dias limpo',
    icon: '🕊️',
    category: 'diamond',
    requirement: 365,
    xpReward: 25000,
    checkProgress: (stats) => stats.cleanDays || 0,
  },

  // SPECIAL - Conquistas Especiais
  {
    id: 'level-10',
    type: 'special',
    name: 'Nível 10',
    description: 'Alcance o nível 10',
    icon: '🎖️',
    category: 'gold',
    requirement: 10,
    xpReward: 500,
    checkProgress: (stats) => stats.level || 0,
  },
  {
    id: 'level-25',
    type: 'special',
    name: 'Nível 25',
    description: 'Alcance o nível 25',
    icon: '🏅',
    category: 'platinum',
    requirement: 25,
    xpReward: 2000,
    checkProgress: (stats) => stats.level || 0,
  },
  {
    id: 'level-50',
    type: 'special',
    name: 'Nível 50',
    description: 'Alcance o nível 50',
    icon: '👑',
    category: 'diamond',
    requirement: 50,
    xpReward: 10000,
    checkProgress: (stats) => stats.level || 0,
  },
];

export const CATEGORY_COLORS = {
  bronze: 'from-amber-700 to-amber-900',
  silver: 'from-gray-400 to-gray-600',
  gold: 'from-yellow-400 to-yellow-600',
  platinum: 'from-cyan-400 to-blue-600',
  diamond: 'from-purple-400 to-pink-600',
};

export const CATEGORY_NAMES = {
  bronze: 'Bronze',
  silver: 'Prata',
  gold: 'Ouro',
  platinum: 'Platina',
  diamond: 'Diamante',
};

// Made with Bob
