// Biblioteca de Hábitos Prontos
// 50+ hábitos categorizados para facilitar o onboarding

export interface HabitTemplate {
  id: string;
  name: string;
  description: string;
  category: 'health' | 'productivity' | 'mindfulness' | 'social' | 'learning';
  duration: number; // minutos
  frequency: 'daily' | 'weekly';
  suggestedTime?: string;
  icon: string;
  difficulty: 'easy' | 'medium' | 'hard';
  benefits: string[];
}

export const HABIT_CATEGORIES = {
  health: { name: 'Saúde & Corpo', icon: '💪', color: 'green' },
  productivity: { name: 'Produtividade', icon: '🎯', color: 'blue' },
  mindfulness: { name: 'Mente & Bem-estar', icon: '🧘', color: 'purple' },
  social: { name: 'Social & Relacionamentos', icon: '👥', color: 'pink' },
  learning: { name: 'Aprendizado', icon: '📚', color: 'yellow' },
};

export const HABITS_LIBRARY: HabitTemplate[] = [
  // SAÚDE & CORPO (15 hábitos)
  {
    id: 'drink-water-morning',
    name: 'Beber água ao acordar',
    description: '500ml de água logo ao acordar para hidratar o corpo',
    category: 'health',
    duration: 2,
    frequency: 'daily',
    suggestedTime: '07:00',
    icon: '💧',
    difficulty: 'easy',
    benefits: ['Hidratação', 'Acelera metabolismo', 'Melhora digestão'],
  },
  {
    id: 'morning-stretch',
    name: 'Alongamento matinal',
    description: '10 minutos de alongamento ao acordar',
    category: 'health',
    duration: 10,
    frequency: 'daily',
    suggestedTime: '07:10',
    icon: '🤸',
    difficulty: 'easy',
    benefits: ['Flexibilidade', 'Reduz dores', 'Energia'],
  },
  {
    id: 'workout',
    name: 'Treino físico',
    description: 'Exercício físico (academia, corrida, etc)',
    category: 'health',
    duration: 45,
    frequency: 'daily',
    suggestedTime: '06:00',
    icon: '🏋️',
    difficulty: 'medium',
    benefits: ['Força', 'Saúde cardiovascular', 'Bem-estar'],
  },
  {
    id: 'walk',
    name: 'Caminhada',
    description: 'Caminhada leve de 20 minutos',
    category: 'health',
    duration: 20,
    frequency: 'daily',
    suggestedTime: '18:00',
    icon: '🚶',
    difficulty: 'easy',
    benefits: ['Circulação', 'Clareza mental', 'Vitamina D'],
  },
  {
    id: 'healthy-breakfast',
    name: 'Café da manhã saudável',
    description: 'Refeição balanceada com proteína e fibras',
    category: 'health',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '07:30',
    icon: '🥗',
    difficulty: 'easy',
    benefits: ['Energia', 'Nutrição', 'Foco'],
  },
  {
    id: 'no-sugar',
    name: 'Dia sem açúcar',
    description: 'Evitar açúcar refinado durante o dia',
    category: 'health',
    duration: 1,
    frequency: 'daily',
    icon: '🚫🍬',
    difficulty: 'medium',
    benefits: ['Saúde', 'Energia estável', 'Foco'],
  },
  {
    id: 'sleep-schedule',
    name: 'Dormir no horário',
    description: 'Ir para cama antes das 23h',
    category: 'health',
    duration: 5,
    frequency: 'daily',
    suggestedTime: '22:45',
    icon: '😴',
    difficulty: 'medium',
    benefits: ['Sono de qualidade', 'Recuperação', 'Energia'],
  },
  {
    id: 'vitamins',
    name: 'Tomar vitaminas',
    description: 'Suplementação diária (vitamina D, ômega 3, etc)',
    category: 'health',
    duration: 2,
    frequency: 'daily',
    suggestedTime: '08:00',
    icon: '💊',
    difficulty: 'easy',
    benefits: ['Imunidade', 'Saúde', 'Prevenção'],
  },
  {
    id: 'posture-check',
    name: 'Checar postura',
    description: 'Verificar e corrigir postura a cada hora',
    category: 'health',
    duration: 1,
    frequency: 'daily',
    icon: '🧍',
    difficulty: 'easy',
    benefits: ['Saúde da coluna', 'Previne dores', 'Consciência corporal'],
  },
  {
    id: 'eye-rest',
    name: 'Descanso visual (20-20-20)',
    description: 'A cada 20min, olhar 20s para algo a 20 pés de distância',
    category: 'health',
    duration: 1,
    frequency: 'daily',
    icon: '👁️',
    difficulty: 'easy',
    benefits: ['Saúde ocular', 'Reduz fadiga', 'Previne miopia'],
  },
  {
    id: 'floss',
    name: 'Usar fio dental',
    description: 'Higiene bucal completa com fio dental',
    category: 'health',
    duration: 3,
    frequency: 'daily',
    suggestedTime: '22:00',
    icon: '🦷',
    difficulty: 'easy',
    benefits: ['Saúde bucal', 'Previne doenças', 'Hálito'],
  },
  {
    id: 'cold-shower',
    name: 'Banho frio',
    description: '2 minutos de água fria no final do banho',
    category: 'health',
    duration: 2,
    frequency: 'daily',
    suggestedTime: '07:00',
    icon: '🚿',
    difficulty: 'hard',
    benefits: ['Circulação', 'Imunidade', 'Energia'],
  },
  {
    id: 'no-phone-bed',
    name: 'Sem celular na cama',
    description: 'Não usar celular 30min antes de dormir',
    category: 'health',
    duration: 1,
    frequency: 'daily',
    suggestedTime: '22:00',
    icon: '📵',
    difficulty: 'medium',
    benefits: ['Sono de qualidade', 'Melatonina', 'Descanso mental'],
  },
  {
    id: 'sunlight',
    name: 'Exposição solar',
    description: '15 minutos de sol pela manhã',
    category: 'health',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '08:00',
    icon: '☀️',
    difficulty: 'easy',
    benefits: ['Vitamina D', 'Ritmo circadiano', 'Humor'],
  },
  {
    id: 'breathing',
    name: 'Respiração profunda',
    description: '5 minutos de respiração consciente (4-7-8)',
    category: 'health',
    duration: 5,
    frequency: 'daily',
    suggestedTime: '12:00',
    icon: '🌬️',
    difficulty: 'easy',
    benefits: ['Calma', 'Oxigenação', 'Foco'],
  },

  // PRODUTIVIDADE (12 hábitos)
  {
    id: 'make-bed',
    name: 'Arrumar a cama',
    description: 'Primeira tarefa do dia - arrumar a cama',
    category: 'productivity',
    duration: 3,
    frequency: 'daily',
    suggestedTime: '07:00',
    icon: '🛏️',
    difficulty: 'easy',
    benefits: ['Senso de realização', 'Disciplina', 'Ambiente organizado'],
  },
  {
    id: 'plan-day',
    name: 'Planejar o dia',
    description: 'Definir 3 MITs (Most Important Tasks) do dia',
    category: 'productivity',
    duration: 10,
    frequency: 'daily',
    suggestedTime: '07:30',
    icon: '📋',
    difficulty: 'easy',
    benefits: ['Clareza', 'Foco', 'Produtividade'],
  },
  {
    id: 'deep-work',
    name: 'Trabalho profundo',
    description: '2 horas de trabalho focado sem interrupções',
    category: 'productivity',
    duration: 120,
    frequency: 'daily',
    suggestedTime: '09:00',
    icon: '🎯',
    difficulty: 'hard',
    benefits: ['Produtividade', 'Qualidade', 'Flow'],
  },
  {
    id: 'inbox-zero',
    name: 'Inbox Zero',
    description: 'Processar todos os emails e mensagens',
    category: 'productivity',
    duration: 20,
    frequency: 'daily',
    suggestedTime: '16:00',
    icon: '📧',
    difficulty: 'medium',
    benefits: ['Organização', 'Clareza mental', 'Controle'],
  },
  {
    id: 'review-day',
    name: 'Revisar o dia',
    description: 'Reflexão sobre o que funcionou e o que melhorar',
    category: 'productivity',
    duration: 10,
    frequency: 'daily',
    suggestedTime: '21:00',
    icon: '📝',
    difficulty: 'easy',
    benefits: ['Aprendizado', 'Melhoria contínua', 'Consciência'],
  },
  {
    id: 'clean-desk',
    name: 'Limpar mesa',
    description: 'Organizar e limpar espaço de trabalho',
    category: 'productivity',
    duration: 5,
    frequency: 'daily',
    suggestedTime: '18:00',
    icon: '🧹',
    difficulty: 'easy',
    benefits: ['Foco', 'Ambiente agradável', 'Produtividade'],
  },
  {
    id: 'no-social-media',
    name: 'Sem redes sociais',
    description: 'Evitar redes sociais durante horário de trabalho',
    category: 'productivity',
    duration: 1,
    frequency: 'daily',
    icon: '🚫📱',
    difficulty: 'hard',
    benefits: ['Foco', 'Tempo', 'Produtividade'],
  },
  {
    id: 'batch-tasks',
    name: 'Agrupar tarefas similares',
    description: 'Fazer todas as tarefas similares de uma vez',
    category: 'productivity',
    duration: 30,
    frequency: 'daily',
    suggestedTime: '14:00',
    icon: '📦',
    difficulty: 'medium',
    benefits: ['Eficiência', 'Menos context switching', 'Velocidade'],
  },
  {
    id: 'weekly-review',
    name: 'Revisão semanal',
    description: 'Revisar semana e planejar próxima',
    category: 'productivity',
    duration: 30,
    frequency: 'weekly',
    suggestedTime: '09:00',
    icon: '📊',
    difficulty: 'medium',
    benefits: ['Perspectiva', 'Planejamento', 'Alinhamento'],
  },
  {
    id: 'learn-shortcut',
    name: 'Aprender atalho novo',
    description: 'Aprender um atalho de teclado por dia',
    category: 'productivity',
    duration: 5,
    frequency: 'daily',
    icon: '⌨️',
    difficulty: 'easy',
    benefits: ['Velocidade', 'Eficiência', 'Maestria'],
  },
  {
    id: 'pomodoro-session',
    name: 'Sessão Pomodoro',
    description: '25 minutos de foco total + 5 min pausa',
    category: 'productivity',
    duration: 30,
    frequency: 'daily',
    icon: '🍅',
    difficulty: 'easy',
    benefits: ['Foco', 'Produtividade', 'Energia'],
  },
  {
    id: 'time-blocking',
    name: 'Time Blocking',
    description: 'Bloquear horários no calendário para tarefas importantes',
    category: 'productivity',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '07:00',
    icon: '📅',
    difficulty: 'medium',
    benefits: ['Controle do tempo', 'Foco', 'Priorização'],
  },

  // MENTE & BEM-ESTAR (12 hábitos)
  {
    id: 'meditation',
    name: 'Meditação',
    description: '10 minutos de meditação mindfulness',
    category: 'mindfulness',
    duration: 10,
    frequency: 'daily',
    suggestedTime: '07:00',
    icon: '🧘',
    difficulty: 'medium',
    benefits: ['Calma', 'Foco', 'Clareza mental'],
  },
  {
    id: 'gratitude',
    name: 'Diário de gratidão',
    description: 'Escrever 3 coisas pelas quais é grato',
    category: 'mindfulness',
    duration: 5,
    frequency: 'daily',
    suggestedTime: '21:00',
    icon: '🙏',
    difficulty: 'easy',
    benefits: ['Felicidade', 'Perspectiva', 'Bem-estar'],
  },
  {
    id: 'journaling',
    name: 'Journaling',
    description: 'Escrever pensamentos e reflexões do dia',
    category: 'mindfulness',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '21:00',
    icon: '📔',
    difficulty: 'easy',
    benefits: ['Autoconhecimento', 'Clareza', 'Processamento emocional'],
  },
  {
    id: 'no-news',
    name: 'Sem notícias negativas',
    description: 'Evitar consumo excessivo de notícias',
    category: 'mindfulness',
    duration: 1,
    frequency: 'daily',
    icon: '📰🚫',
    difficulty: 'medium',
    benefits: ['Paz mental', 'Menos ansiedade', 'Foco no controlável'],
  },
  {
    id: 'nature',
    name: 'Contato com natureza',
    description: '20 minutos em ambiente natural',
    category: 'mindfulness',
    duration: 20,
    frequency: 'daily',
    suggestedTime: '17:00',
    icon: '🌳',
    difficulty: 'easy',
    benefits: ['Calma', 'Conexão', 'Reduz estresse'],
  },
  {
    id: 'music',
    name: 'Ouvir música',
    description: 'Momento dedicado a ouvir música que gosta',
    category: 'mindfulness',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '19:00',
    icon: '🎵',
    difficulty: 'easy',
    benefits: ['Prazer', 'Relaxamento', 'Humor'],
  },
  {
    id: 'digital-detox',
    name: 'Detox digital',
    description: '1 hora sem telas (celular, computador, TV)',
    category: 'mindfulness',
    duration: 60,
    frequency: 'daily',
    suggestedTime: '20:00',
    icon: '📵',
    difficulty: 'hard',
    benefits: ['Descanso mental', 'Presença', 'Sono'],
  },
  {
    id: 'affirmations',
    name: 'Afirmações positivas',
    description: 'Repetir 5 afirmações positivas',
    category: 'mindfulness',
    duration: 5,
    frequency: 'daily',
    suggestedTime: '07:00',
    icon: '💭',
    difficulty: 'easy',
    benefits: ['Autoestima', 'Mindset', 'Confiança'],
  },
  {
    id: 'hobby',
    name: 'Praticar hobby',
    description: 'Tempo dedicado a um hobby prazeroso',
    category: 'mindfulness',
    duration: 30,
    frequency: 'daily',
    suggestedTime: '19:00',
    icon: '🎨',
    difficulty: 'easy',
    benefits: ['Prazer', 'Criatividade', 'Flow'],
  },
  {
    id: 'laugh',
    name: 'Rir',
    description: 'Assistir algo engraçado ou conversar com amigos',
    category: 'mindfulness',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '20:00',
    icon: '😂',
    difficulty: 'easy',
    benefits: ['Humor', 'Endorfina', 'Bem-estar'],
  },
  {
    id: 'visualization',
    name: 'Visualização',
    description: 'Visualizar objetivos e dia ideal',
    category: 'mindfulness',
    duration: 10,
    frequency: 'daily',
    suggestedTime: '07:00',
    icon: '🎯',
    difficulty: 'medium',
    benefits: ['Motivação', 'Clareza', 'Foco'],
  },
  {
    id: 'no-complain',
    name: 'Dia sem reclamar',
    description: 'Evitar reclamações durante o dia',
    category: 'mindfulness',
    duration: 1,
    frequency: 'daily',
    icon: '🤐',
    difficulty: 'hard',
    benefits: ['Positividade', 'Gratidão', 'Energia'],
  },

  // SOCIAL & RELACIONAMENTOS (6 hábitos)
  {
    id: 'call-family',
    name: 'Ligar para família',
    description: 'Conversar com familiar ou amigo próximo',
    category: 'social',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '19:00',
    icon: '📞',
    difficulty: 'easy',
    benefits: ['Conexão', 'Relacionamentos', 'Apoio'],
  },
  {
    id: 'compliment',
    name: 'Elogiar alguém',
    description: 'Fazer um elogio genuíno a alguém',
    category: 'social',
    duration: 2,
    frequency: 'daily',
    icon: '💝',
    difficulty: 'easy',
    benefits: ['Positividade', 'Conexão', 'Gentileza'],
  },
  {
    id: 'quality-time',
    name: 'Tempo de qualidade',
    description: 'Tempo focado com pessoa importante (sem distrações)',
    category: 'social',
    duration: 30,
    frequency: 'daily',
    suggestedTime: '19:00',
    icon: '👥',
    difficulty: 'medium',
    benefits: ['Relacionamentos', 'Conexão', 'Amor'],
  },
  {
    id: 'help-someone',
    name: 'Ajudar alguém',
    description: 'Fazer algo útil para outra pessoa',
    category: 'social',
    duration: 15,
    frequency: 'daily',
    icon: '🤝',
    difficulty: 'easy',
    benefits: ['Propósito', 'Conexão', 'Bem-estar'],
  },
  {
    id: 'active-listening',
    name: 'Escuta ativa',
    description: 'Praticar escuta ativa em conversas',
    category: 'social',
    duration: 10,
    frequency: 'daily',
    icon: '👂',
    difficulty: 'medium',
    benefits: ['Relacionamentos', 'Empatia', 'Conexão'],
  },
  {
    id: 'social-event',
    name: 'Evento social',
    description: 'Participar de evento ou encontro social',
    category: 'social',
    duration: 120,
    frequency: 'weekly',
    suggestedTime: '19:00',
    icon: '🎉',
    difficulty: 'medium',
    benefits: ['Conexão', 'Diversão', 'Rede de apoio'],
  },

  // APRENDIZADO (7 hábitos)
  {
    id: 'read',
    name: 'Ler',
    description: '30 minutos de leitura (livros, artigos)',
    category: 'learning',
    duration: 30,
    frequency: 'daily',
    suggestedTime: '21:00',
    icon: '📚',
    difficulty: 'easy',
    benefits: ['Conhecimento', 'Vocabulário', 'Foco'],
  },
  {
    id: 'learn-new',
    name: 'Aprender algo novo',
    description: 'Estudar novo conceito ou habilidade',
    category: 'learning',
    duration: 30,
    frequency: 'daily',
    suggestedTime: '20:00',
    icon: '🎓',
    difficulty: 'medium',
    benefits: ['Crescimento', 'Neuroplasticidade', 'Competência'],
  },
  {
    id: 'podcast',
    name: 'Ouvir podcast educativo',
    description: 'Podcast sobre tema de interesse',
    category: 'learning',
    duration: 30,
    frequency: 'daily',
    suggestedTime: '08:00',
    icon: '🎧',
    difficulty: 'easy',
    benefits: ['Conhecimento', 'Perspectivas', 'Inspiração'],
  },
  {
    id: 'flashcards',
    name: 'Revisar flashcards',
    description: 'Spaced repetition de conteúdo estudado',
    category: 'learning',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '08:00',
    icon: '🗂️',
    difficulty: 'easy',
    benefits: ['Memorização', 'Retenção', 'Domínio'],
  },
  {
    id: 'write-summary',
    name: 'Resumir aprendizado',
    description: 'Escrever resumo do que aprendeu (Técnica Feynman)',
    category: 'learning',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '21:00',
    icon: '✍️',
    difficulty: 'medium',
    benefits: ['Compreensão', 'Retenção', 'Clareza'],
  },
  {
    id: 'language',
    name: 'Praticar idioma',
    description: 'Estudar novo idioma (Duolingo, etc)',
    category: 'learning',
    duration: 15,
    frequency: 'daily',
    suggestedTime: '08:00',
    icon: '🌍',
    difficulty: 'medium',
    benefits: ['Bilinguismo', 'Cognição', 'Oportunidades'],
  },
  {
    id: 'teach',
    name: 'Ensinar algo',
    description: 'Explicar conceito para alguém ou escrever sobre',
    category: 'learning',
    duration: 20,
    frequency: 'weekly',
    icon: '👨‍🏫',
    difficulty: 'medium',
    benefits: ['Domínio', 'Clareza', 'Contribuição'],
  },
];

// Função para buscar hábitos por categoria
export const getHabitsByCategory = (category: HabitTemplate['category']) => {
  return HABITS_LIBRARY.filter(habit => habit.category === category);
};

// Função para buscar hábitos por dificuldade
export const getHabitsByDifficulty = (difficulty: HabitTemplate['difficulty']) => {
  return HABITS_LIBRARY.filter(habit => habit.difficulty === difficulty);
};

// Função para buscar hábitos rápidos (até 10 minutos)
export const getQuickHabits = () => {
  return HABITS_LIBRARY.filter(habit => habit.duration <= 10);
};

// Função para recomendar hábitos para iniciantes
export const getBeginnerHabits = () => {
  return HABITS_LIBRARY.filter(habit => habit.difficulty === 'easy' && habit.duration <= 15);
};

// Made with Bob
